Projectile editor
Nine-Byte-Warriors/five-nights-of-farming pull request #108
Opened 2023-01-19 16:13 UTC by BlackRece

**Describe your changes**
Fully functioning Projectile editor that saves and loads to json file and when clicking "Test Fire" will show how the projectiles will look.

**Screenshots**
![image](https://user-images.githubusercontent.com/19497851/213494229-2665b393-ac96-47ac-92cc-353a8a0379fb.png)

2023-01-19 17:07 UTC, juliusz-kaczmarek requested changes
The wiggle doesn't seem to happen, it's more like going in some weird pattern, not sure why this is happening, but I have a suspicion the sine wave formula is applied incorrectly

2023-01-19 17:07 UTC, juliusz-kaczmarek commented on Studio Sim/Objects/Projectile.h
> +
This might be incorrect

2023-01-19 17:07 UTC, juliusz-kaczmarek commented on Studio Sim/Projectile Editor/ProjectileEditor.cpp
> +						0.1f, -360.0f, 360.0f, "%.2f");
This might be incorrect

2023-01-19 17:13 UTC, BlackRece commented on Studio Sim/Objects/Projectile.h
> +
I think the effect of this formula is correct but it's the wrong formula.
Please suggest what formula you wish for me to use/simulate.

2023-01-19 17:16 UTC, BlackRece commented on Studio Sim/Projectile Editor/ProjectileEditor.cpp
> +						0.1f, -360.0f, 360.0f, "%.2f");
![image](https://user-images.githubusercontent.com/19497851/213514460-da5f596a-9fa8-47bb-849a-ca884d862e8d.png)
Currently only displays as "Wave" have corrected and will commit.

2023-01-19 17:17 UTC, BlackRece commented on Studio Sim/Projectile Editor/ProjectileEditor.cpp
> +						0.1f, -360.0f, 360.0f, "%.2f");
Will also change depending on the requirements of a team-agreed wave function.

2023-01-19 17:22 UTC, juliusz-kaczmarek commented on Studio Sim/Projectile Editor/ProjectileEditor.cpp
> +						0.1f, -360.0f, 360.0f, "%.2f");
![image](https://user-images.githubusercontent.com/57526276/213515750-54254c95-8f4d-43fc-9839-58848da5908b.png)
Expected fly pattern with basic sine wave projectile

2023-01-20 04:12 UTC, kyle-robinson requested changes
Other than the changes that Juliusz requested, I think I'm happy enough.

I'll mark this as a change request though, since after trying to resolve the conflicts, it doesn't seem like the editor is working anymore. Or at the very least, it doesn't look like the projectiles are doing anything, and when trying to modify any of the sliders after loading a pattern causes a crash.

Might need to go through this together at some point tomorrow. I won't push the changes yet since it is technically broken on my end at the minute 😏

2023-01-20 13:01 UTC, kyle-robinson approved these changes

2023-01-20 13:02 UTC, juliusz-kaczmarek approved these changes

2023-01-20 15:24 UTC, merged