Projectiles, Manager and Pool
Nine-Byte-Warriors/five-nights-of-farming pull request #48
Opened 2023-01-13 20:44 UTC by BlackRece

When Button is clicked, a dead projectile is emitted from the player in the direction of the enemy limited by a hardcoded value which is to be retrieved from a JSON file along with other projectile settings such as speed and lifetime.

2023-01-13 21:37 UTC, kyle-robinson requested changes
Coolio 😎 👍🏻 
There will probably be some build errors on release even after making those changes, and after pushing to master, since there's no preprocessor stuff for imgui. I can add that after the PR gets merged tho, so don't worry about it.

2023-01-13 21:37 UTC, kyle-robinson commented on Studio Sim/Utility/structures.h
> +};
Could you move this out to the ProjectileManager class? This class is really only reserved for structs to be used as constant buffers. Tbf, I probably should have made this more clear. Other than that, everything's looking cool 😎 👍🏻

2023-01-13 21:37 UTC, kyle-robinson commented on Studio Sim/Input/Input.cpp
> +		}
Just drawing attention from the other comment, now that I found it 😎 👍🏻

2023-01-13 21:37 UTC, kyle-robinson commented on Studio Sim/Input/Input.cpp
> +        EventSystem::Instance()->AddEvent(EVENTID::MousePosition, pMousePos);
Now that I think about it, I don't think this is needed either. I pushed a few changes to master, and I'm pretty sure I moved this out to the window container 😎 👍🏻

2023-01-13 21:37 UTC, kyle-robinson commented on Studio Sim/Window/WindowContainer.cpp
> +            EventSystem::Instance()->AddEvent( EVENTID::LeftMouseClick, mousePos );
Does this event actually do anything atm? If not, I'd get rid of it here, and I think there was some stuff in the input class as well 😎 👍🏻

2023-01-14 08:42 UTC, BlackRece commented on Studio Sim/Utility/structures.h
> +};
then it should be renamed to be clear.
that's uni's bad habit of sticking all structs in one file regardless of the use case.
however, I ended up not using this struct so it can be removed altogether.

2023-01-14 08:47 UTC, BlackRece commented on Studio Sim/Window/WindowContainer.cpp
> +            EventSystem::Instance()->AddEvent( EVENTID::LeftMouseClick, mousePos );
in general terms and in keeping with the aims of the project wanting to use keyboard/mouse controls, these events should still be emitted even though I'm not using them atm.
thoughts?

2023-01-14 08:53 UTC, BlackRece commented on Studio Sim/Input/Input.cpp
> +		}
i wonder if we ever need raw mouse events (from win32) ...
imgui is only used in the editior...
so win32 would be the fallback...
I think its complex enough to warrant a mini system that decides whether the event is emitted from imgui or win32, so that the eventsystem doesn't care thereby not having separate events for both.
Thoughts?

2023-01-14 08:54 UTC, BlackRece commented on Studio Sim/Input/Input.cpp
> +        EventSystem::Instance()->AddEvent(EVENTID::MousePosition, pMousePos);
see https://github.com/Nine-Byte-Warriors/five-nights-of-farming/pull/48#discussion_r1070237425

2023-01-14 15:42 UTC, kyle-robinson commented on Studio Sim/Utility/structures.h
> +};
Ah ok. Just be sure to remove it, then commit that change and resolve this conversation 😎 👍🏻

2023-01-14 15:47 UTC, kyle-robinson commented on Studio Sim/Input/Input.cpp
> +		}
Yeah, so in the WindowContainer atm, there is a system that checks for ImGUI input first. If so, it doesn't use the Win32 input. So atm, the Win32 input is never really used in the editor, but since I've added all the preprocessor stuff, it is used in Release mode, which would basically be the actual game.

Idk, I think I'll probably have to look at a more versatile solution for this. I'll marked this as resolved and then when this ends up getting merged, I'll try to figure out the best approach for this

2023-01-14 15:49 UTC, kyle-robinson commented on Studio Sim/Window/WindowContainer.cpp
> +            EventSystem::Instance()->AddEvent( EVENTID::LeftMouseClick, mousePos );
Yeah, I think what I'll do is go back and setup all of the events that we currently have listed so they don't get fired from like 5 different places at the same time. I think I agree with them not necessarily being used, but only in the case where it doesn't cause issue - which I don't think this one is 😎 👍🏻

2023-01-14 15:54 UTC, kyle-robinson commented
Oh, also, just quickly check the MSBuild details. It's throwing an error on some undeclared identifiers. Might be worth checking that release builds properly as well since that can sometimes be the reason that it doesn't work.

You can just add it on as a commit to the branch and it'll get added to this PR. It should just start a build of the project again when you do

2023-01-15 01:50 UTC, kyle-robinson approved these changes

2023-01-15 01:50 UTC, merged